[project]
name = "car-solver"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "pyvista",
    "matplotlib",
    "python-dotenv",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]
parallel = ["pytest-xdist"]

[tool.pytest.ini_options]
testpaths = ["tests"]
